(require 'package)
(setq package-archives '(("gnu"       . "http://elpa.gnu.org/packages/")
			             ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa"     . "http://melpa.milkbox.net/packages/")))

(setq org-directory "/home/todd/Documents/org")
(setq speedbar-font "Liberation Sans-10")
(setq sr-speedbar-default-width 25)
(setq sr-speedbar-max-width 25)
(setq sb-height 110)
(setq sb-face "Iosevka SS03")
;;(add-to-list 'default-frame-alist '(font . "Hack-13"))
(add-to-list 'default-frame-alist '(font . "Iosevka SS03-14"))
(load-theme 'tkf-dark 1)
(setq inferior-lisp-program "/usr/bin/sbcl")
