(require 'package)
(setq package-archives '(("gnu"       . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa"     . "http://melpa.milkbox.net/packages/")))
(setq org-directory "/home/todd/Documents/Notes/org")
;;(setq speedbar-font "Iosevka SS03 Light-8")
;;(setq speedbar-font "Hack Italic-10")
(setq sr-speedbar-default-width 30)
(setq sr-speedbar-max-width 30)
(setq sb-height 110)
;;(setq sb-face "Iosevka SS03 Light")
(setq sb-face "Hack Italic")
;;(add-to-list 'default-frame-alist '(font . "Hack-14"))
(add-to-list 'default-frame-alist '(font . "Iosevka SS03-13"))
;;(add-to-list 'default-frame-alist '(font . "Go Mono-12"))
(load-theme 'tkf-dark 1)
;;(setq inferior-lisp-program "/usr/bin/sbcl")
